print("Course ---- Credits")
print("ENVIRONMENT AND SUSTAINABILITY ---- 3")
print("Capstone Design ---- 1")
print("SEMINAR ON SPECIAL TOPICS IN EMERGING AREAS ---- 1")
print("Undergraduate Research in Computer Science ---- 1")
print("HIGH PERFORMANCE COMPUTING ---- 4")
print("Software Project Management ---- 3")
print("DevOps Engineering Practice ---- 3")
